name: CI/CD for EntryTracker

on:
  push:
    branches:
      - main

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: שלב 1: הורדת קוד המקור
        uses: actions/checkout@v3

      - name: שלב 2: התקנת פייתון
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: שלב 3: התקנת תלותים
        run: |
          pip install -r requirements.txt

      - name: שלב 4: הרצת האפליקציה ברקע
        run: |
          python app.py &
          sleep 5  # מחכה שהשרת יעלה

      - name: שלב 5: בדיקת curl (בדיקת יחידה)
        run: |
          curl http://localhost:5000 | grep "EntryTracker" || exit 1

      - name: שלב 6: בניית Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/entrytracker:latest .

      - name: שלב 7: בדיקות End-to-End עם docker-compose
        run: |
          docker-compose up -d
          sleep 10
          curl http://localhost:5000 | grep "EntryTracker" || exit 1
          docker-compose down

      - name: שלב 8: התחברות ל-DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: שלב 9: דחיפת image ל-DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/entrytracker:latest

